### PR TITLE
Some new German translation

### PR DESCRIPTION
**Pull request by petrisch**
So I guess I better send this in before things diverge too much.
My plan is to do the rest as well, but son't know when.

### CODE REVIEW

**Comment by fdncred** [comment]
Thanks

**Comment by hustcer** [comment]
@petrisch Can you do a rebase from the latest main branch?
BTW: We have upgrade to vuepress-next a few hours ago, and the code import syntax changed, please check `https://github.com/nushell/nushell.github.io/blob/main/book/installation.md` for reference

**Comment by petrisch** [comment]
@hustcer sorry for beeing late. And I don't know if I did the right thing now.
Also I don't think I have a code import in these files, but there is probably some in the german translation I will look for them.

**Comment by hustcer** [comment]
@petrisch Yeah, you have code import in these new translations such like `<<< @/snippets/*`, I have already fixed the old translations

**Comment by hustcer** [comment]
@petrisch Do you need any help? Or I can merge your PR and fix it by myself

**Comment by petrisch** [comment]
@hustcer oh now I see. Ok let me try to correct that. Will not be before tomorow I guess.

**Comment by petrisch** [comment]
ahhh... ok now I need help. I have to accept, that I'm still a noob in git. I changed the snippets and then rebased my changes to be the latest commit. But thats not how rebase works right? I could just delete this and reapply my changes to a new fork. But what would have been the right approach?

**Comment by hustcer** [comment]
@petrisch You have just modified 4 files. The easiest way may be: 

1. Create a new branch from the official main branch
2. Then checkout the 4 files you have translated to that branch, copy works too
3. Close this PR and create a new PR from that branch

You can also Add me as  a Collaborator of https://github.com/petrisch/nushell.github.io, and I will do the rest for you

**Pull request closed without merging**
