### PR TITLE
Update environment.md

### PR DESCRIPTION
**Pull request by chtenb**
Add an example of how to extend the path variable, which I think is a very common use case that people would search for.

### CODE REVIEW

**Comment by fdncred** [comment]
good add. can you also add an example with `append` so people know that both `prepend` and `append` exist?

**Comment by chtenb** [comment]
@fdncred I've mentioned append as well

**Comment by fdncred** [comment]
thanks

**Comment by rgwood** [comment]
Thanks! Questions about this come up a lot, good to have it documented

**Pull request merged**
