### PR TITLE
add #8189 to the release notes

### PR DESCRIPTION
**Pull request by amtoine**
hellord :wave: 

this was technically part of the last release but i discovered how this all works the very night of the `0.77.0`...

hope you'll like it, that's quite a nice change to the `help` pages i think :relieved:

### CODE REVIEW

**Comment by amtoine** [comment]
conflicts solve :ok_hand: :yum:

**Comment by sholderbach** [comment]
Thanks for being proactive around the release notes. I think for features that merged in previous releases I think it is better to expand the respective older release notes (if it is not a secret behavior we stabilize later). 

Not to steal your thunder but I think for this smaller quality-of-life improvement I would cut out the before/after comparison to be economical with the readers attention.

**Comment by amtoine** [comment]
@sholderbach 

of course, no problem !!

i thought the previous release note was "closed" after the release was made :open_mouth: 
can i open a PR against the previous release note and see all this there, not in the upcoming release? :yum:

**Comment by sholderbach** [comment]
You can just target the file of the last release (or any other release note if we made a mistake there)

**Comment by amtoine** [comment]
> You can just target the file of the last release (or any other release note if we made a mistake there)
>
nice, cool

i'll close this and redo the PR, thanks for the clarification :relieved:

**Pull request closed without merging**
