### PR TITLE
Remove unnecessary 0.59 binaries

### PR DESCRIPTION
**Pull request by hustcer**
Remove unnecessary 0.59 binaries, It's old and outdated

### CODE REVIEW

**Comment by fdncred** [comment]
This is the only copy we have of these files. Is there somewhere we can place them, like in a release somewhere, so we don't lose them?

**Comment by hustcer** [comment]
If you just want to backup them somewhere and don't care about where they are, I think I can create a release here https://github.com/hustcer/nu-release/releases and upload these binaries

**Comment by fdncred** [comment]
can we put them in the releases of this repo?

**Comment by hustcer** [comment]
> can we put them in the releases of this repo?

Yes, but this repo need to be cleaned, and all the tags will be removed after the clean

**Comment by fdncred** [comment]
what about uploading those binaries as an old release, after it's cleaned?

**Review by amtoine — APPROVED** [review]
this is all fine with me if it speeds up `git clone`ing :ok_hand:

**Pull request merged**
