### PR TITLE
Release notes for `0.86`

### PR DESCRIPTION
**Pull request by amtoine**
Please add your new features and breaking changes to the release notes
by opening PRs against the `release-notes-0.86` branch.

## TODO
- [x] look at interesting contributions
- [x] write all the sections
- [x] order the sections by interest
- [x] add the breaking changes
- [x] detail the breaking changes
- [x] add the full changelog
- [x] land https://github.com/nushell/nushell/pull/10342
- [x] land https://github.com/nushell/nushell/pull/10341

### CODE REVIEW

**Comment by amtoine** [comment]
related to
- https://github.com/nushell/nu_scripts/pull/618

i've added some of the sections titles we have been using for a few releases now :yum:

**Comment by fdncred** [comment]
Are `release-note-mention` label PRs included in `interesting contributions`? I always wonder if we're using that label during the release and keep forgetting to check.

**Comment by amtoine** [comment]
> Are `release-note-mention` label PRs included in `interesting contributions`? I always wonder if we're using that label during the release and keep forgetting to check.
>
we might not be really using that label, very true :thinking:

**Comment by hustcer** [comment]
Shall we mention the full featured releases?

**Comment by amtoine** [comment]
> Shall we mention the full featured releases?
>
what do you mean?
`--dataframe` and `--extra`?

**Comment by fdncred** [comment]
@hustcer ya, I think so. We should also mention the "full" assets that we're creating now.

**Comment by hustcer** [comment]
> > Shall we mention the full featured releases?
> 
> what do you mean? `--dataframe` and `--extra`?

I mean this PR: https://github.com/nushell/nushell/pull/10457,  and I see it was marked a `release-note-mention` label already

**Comment by amtoine** [comment]
@hustcer 
for now nushell/nushell#10457 is in the *Platform support* table in the *hall of fame*, maybe it's not in the correct place?

**Comment by hustcer** [comment]
> @hustcer for now [nushell/nushell#10457](https://github.com/nushell/nushell/pull/10457) is in the _Platform support_ table in the _hall of fame_, maybe it's not in the correct place?

I think the platform is okay, thanks

**Pull request merged**
