### PR TITLE
docs(book): Update the "Coming from Bash" page

### PR DESCRIPTION
**Pull request by aslilac**
- `chmod` is totally a thing
- Line continuations have been supported for a while

### CODE REVIEW

**Comment by kubouch** [comment]
Thanks! I wouldn't call it just "line continuation", though. I'd phrase it "Line continuation is possible within a subcommand" or something along these lines.

**Comment by kubouch** [comment]
Actually, also `chmod` is not a Nushell command. It just calls the Linux program but won't work on Windows, for example (or is there chmod on Windows?). You could say that it calls the Linux executable but it's not a part of Nushell.

**Comment by aslilac** [comment]
> `chmod` is not a Nushell command

You could say the same for mkdir, cp, mv, rm, etc. 🤷‍♀️

> I wouldn't call it just "line continuation", though

Yeah, now that you point it out, I feel like "line continuation" might even be a bit too technical of a way to describe it. Lmk what you think of my new proposal!

**Comment by aslilac** [comment]
Actually I just realized Nushell actually *is* normalizing all the commands I listed. 😅 Should we just remove `chmod` then?

**Comment by fdncred** [comment]
If you want to leave it in there, I'd prefix it with a caret, which is the formal way of calling externals in nushell. Like `^chmod`.

**Comment by kubouch** [comment]
I would say that you can run `chmod` as any other external command. The current formulation still suggests that `chmod` is a part of Nushell which isn't true.

**Pull request merged**
