### PR TITLE
Fix search box style, make it wider

### PR DESCRIPTION
**Pull request by hustcer**
Fix search box style, make it wider

### CODE REVIEW

**Comment by fdncred** [comment]
It's not very wide on safari. Not sure why.
Screen Shot 2022-06-03 at 7 42 38 AM

**Comment by hustcer** [comment]
It seems that it's in mobile mode not PC mode

**Comment by fdncred** [comment]
> It seems that it's in mobile mode not PC mode

that's weird. I'm on my Mac.

**Comment by hustcer** [comment]
I think you didn't take a snapshot for the full nav bar. The search box is wider than before, however, it needn't be tooooo wide, there is no need to to that

**Comment by fdncred** [comment]
ya, it wasn't the full bar - just enough to help you see how short the search box was. here's the full bar. 
Screen Shot 2022-06-03 at 8 14 07 AM

it just looks small to me. it works fine though. if this is the way it's supposed to be then that's fine.

**Comment by hustcer** [comment]
I think It's okay, and will work fine on your mobile phone, we should consider for various kinds of devices

**Pull request merged**
