### PR TITLE
Change `wrap` example in merge.md

### PR DESCRIPTION
**Pull request by AlifianK**
Update the example to make it clearer

### CODE REVIEW

**Comment by fdncred** [comment]
Right, ci.  You can't change the merge help because it's auto generated from the rust code and docs are updated upon each release. If you want to change the help for merge, you must change the rust code for merge. Thanks.

**Comment by AlifianK** [comment]
Oh okay, sorry for the noise.

**Comment by fdncred** [comment]
no worries at all. thanks for trying to help.

**Comment by NotTheDr01ds** [comment]
@AlifianK Great suggestion - I went ahead and made the change in the main repo with credit to you.  I know if you don't have the Rust toolchain set up already, it's a bit overkill to have to do so just to make this change.

**Pull request closed without merging**
