### PR TITLE
Coming from bash: xargs

### PR DESCRIPTION
**Pull request by raboof**

### CODE REVIEW

**Comment by jntrnr** [comment]
The `$in` is another good was of doing xargs styles of command. Not sure if you wanted to add that too

**Comment by jntrnr** [comment]
@raboof - are you still interested in working on this? `$in` is probably the clearest way to have xargs-style in Nushell.

**Comment by raboof** [comment]
> @raboof - are you still interested in working on this? `$in` is probably the clearest way to have xargs-style in Nushell.

Sorry, this got left by the wayside because I didn't understand how to use `$in` yet ;). This seems to work?

**Comment by fdncred** [comment]
works for me

**Pull request merged**
