### PR TITLE
Unify the language identifiers of the code blocks to 'sh'

### PR DESCRIPTION
**Pull request by ghaaj**
This PR unifies the language identifiers of the code blocks for installation commands to 'sh'.
Syntax highlighting will be applied to the modified code blocks, and the extra $ sign at the beginning will be removed when copied.

### CODE REVIEW

**Comment by fdncred** [comment]
I'm not sure this is a good change because this is a windows only section and probably no one on windows is running `sh` but it is likely they're running `powershell`.

**Comment by ghaaj** [comment]
Thank you for reviewing. Would the preferred choice then be to keep the language identifier of the `powershell` section as is and delete the $ sign?

**Comment by fdncred** [comment]
ya, good idea

**Comment by fdncred** [comment]
Thanks

**Pull request merged**
