### PR TITLE
book/operators.md: add `not` operator

### PR DESCRIPTION
**Pull request by schuelermine**

### CODE REVIEW

**Comment by kubouch** [comment]
Nice, thanks! Would you mind adding `and` and `or` operators as well? (They are similar to `&&` and `||`.)

**Comment by schuelermine** [comment]
I can’t seem to get them to work, how do they work?

**Comment by schuelermine** [comment]
Oh, OK, I’m not on the latest version, that makes sense

**Comment by schuelermine** [comment]
Does `and` and `or` work just like `&&` and `||` or is there some difference?

**Comment by fdncred** [comment]
> Does `and` and `or` work just like `&&` and `||` or is there some difference?

They're literally the same thing in the code.

https://github.com/nushell/nushell/blob/219c719e986db46b75b8623332e2a23a057b949b/crates/nu-parser/src/parser.rs#L4069-L4070

**Comment by fdncred** [comment]
thanks for the contribution!

**Pull request merged**
