### PR TITLE
Release notes for `0.83`

### PR DESCRIPTION
**Pull request by amtoine**
Please add your new features and breaking changes to the release notes
by opening PRs against the `release-notes-0.83` branch.

- [x] look at interesting contributions
- [x] write all the sections
- [x] order the sections by interest
- [x] add the breaking changes
- [x] detail the breaking changes
- [x] add the full changelog

### CODE REVIEW

**Comment by amtoine** [comment]
i had a look at all the PRs since last release and added in raw tables and sections those that might be of some interest in 996fa120 :relieved:

**Comment by sholderbach** [comment]
Thanks for collecting the current state, I don't think the tables are a particularly helpful presentation to the users so we should change them into more explicit explanations.

**Comment by amtoine** [comment]
> Thanks for collecting the current state, I don't think the tables are a particularly helpful presentation to the users so we should change them into more explicit explanations.
>
yes, of course!

i should have added that this is a temporary document, just listing what is interesting imo :relieved:

**Comment by amtoine** [comment]
same goes with the breaking changes, they are raw right now and should be explained a bit more :wink:

**Pull request merged**
