### PR TITLE
Explain how to run aliased paths

### PR DESCRIPTION
**Pull request by Dan-Gamin**
Just a simple explanation about using the `run-external` command to run aliased paths. 

_(Is there a better name for this?)_

### CODE REVIEW

**Comment by fdncred** [comment]
we shouldn't land this because this is a reserved command that will change in the future. it's not really for use.

**Comment by Dan-Gamin** [comment]
> we shouldn't land this because this is a reserved command that will change in the future. it's not really for use.

Oh.

**Comment by Dan-Gamin** [comment]
I guess this will be put on hold until a better command is finalized.

**Comment by kubouch** [comment]
You can also do `^'some/long/path'` instead of `run-external`

**Comment by Dan-Gamin** [comment]
> You can also do `^'some/long/path'` instead of `run-external`

That's not explained explained in the docs right? (Doing it with commands in the PATH  is explained, doing it with actual path strings is not.

**Comment by kubouch** [comment]
Yeah, it might not be covered well enough. You can do for example this as well: `let cmd = 'some/path/to/command`; ^$cmd` which would also be good to document.

Rather than in the "Aliases" section, I would add it somewhere more appropriate, since it's not alias-specific. For example here: https://www.nushell.sh/book/pipeline.html#working-with-external-commands

**Comment by fdncred** [comment]
thanks for understanding.

**Pull request closed without merging**
