### PR TITLE
Clean up commands

### PR DESCRIPTION
**Pull request by rgwood**
- `update_commands.py` has been replaced by `make_docs.nu`, deleting it
- ~`inc`, `gstat`, and `query*` commands are no longer present in latest Nu; deleting their pages to remove them from the command reference~
- rerunning `make_docs.nu` after registering the `inc`, `gstat`, and `query*` commands, so their docs get updated correctly

### CODE REVIEW

**Comment by fdncred** [comment]
the plugins are in the latest nu. I'm not sure what you're saying about `inc`, `gstat`, and `query`.

**Comment by rgwood** [comment]
@fdncred My bad - I didn't realize those are in plugins. I'm building Nu with `cargo build --features extra` and I don't have those commands, how can I get them?

image

**Comment by fdncred** [comment]
you have to register plugins to use them. `register -e capnp /path/to/nu_plugin_gstat` and the rest of them. you should see them in the `version` command.

**Comment by fdncred** [comment]
I think you're right that the *.py needs to go, but not the rest of the files.

**Comment by rgwood** [comment]
Makes sense. 

The command pages probably need to be updated though. When I have time (tomorrow?) I'll build the plugins, register them, and rerun `make_docs.nu`

**Comment by fdncred** [comment]
Sounds good!

**Comment by rgwood** [comment]
@fdncred Should be good now.

**Comment by jntrnr** [comment]
thanks!

**Pull request merged**
