### PR TITLE
Add Github Actions workflow to check typos

### PR DESCRIPTION
**Pull request by Hofer-Julian**
- Add Github Actions workflow to check typos
- Fix existing typos

### CODE REVIEW

**Comment by fdncred** [comment]
I'm kind of wondering how we can use this effectively so far down stream. For anything that is wrong in the commands, we can't fix it in the docs here. We have to fix it in the rust code because all the command docs are auto generated with a nushell script.

The other changes to pages in the book, and things like that, we can make those changes here just fine.

**Comment by Hofer-Julian** [comment]
> I'm kind of wondering how we can use this effectively so far down stream. For anything that is wrong in the commands, we can't fix it in the docs here. We have to fix it in the rust code because all the command docs are auto generated with a nushell script.

My impression is that `typos` targets code more than it does docs.
But because of that, we could also use it additionally for the nushell code base itself.

**Comment by Hofer-Julian** [comment]
> My impression is that typos targets code more than it does docs.
But because of that, we could also use it additionally for the nushell code base itself.

If you want, I can create a follow up PR there.

**Comment by fdncred** [comment]
I think this is fine for now but the split-by changes will get overwritten if the rust code in nushell isn't changed.

**Pull request merged**
