### PR TITLE
fix colors

### PR DESCRIPTION
**Pull request by er2**
I tried these out and got the error message "expected string, found number-like value (hint: use quotes or backticks)" and that worked.

### CODE REVIEW

**Review by amtoine — APPROVED** [review]
that is a recent change.

thanks for the catch :yum:

**Comment by fdncred** [comment]
Thanks for the change but we cannot make changes to the commands this way because the commands are auto generated with a script. What that means is that the next time we run the script this change will be overwritten. In order for this change to remain, the ansi gradient rust code must be changed. If you'd like to make the change there, we'd accept it.

**Comment by amtoine** [comment]
i did not realize it was in the command page, woopsie :eyes:

**Comment by er2** [comment]
I found that here: https://github.com/nushell/nushell/blame/7413ef28243d7586037b8b0b9133e6e7c7d44255/crates/nu-command/src/platform/ansi/gradient.rs#L75

And it looks like it's already fixed. Does something need to be done to regenerate this markdown?

**Comment by amtoine** [comment]
> Does something need to be done to regenerate this markdown?
>
you need to run the `make_docs.nu` script in the root of this repo.
but this is done around each release, so no need to generate that right now, if i have the full flow of the site correctly in mind :yum:

**Pull request closed without merging**
