### PR TITLE
remove last mentions to `let-env`

### PR DESCRIPTION
**Pull request by amtoine**
this PR
- replaces the `let-env` with `$env.` in the foreign languages
- fixes the English "configuration" page

## TODO
there are still mentions to `let-env` in the following files
- `zh-CN/book/configuration.md`
- `zh-CN/book/modules.md`
- `zh-CN/book/environment.md`
- `de/book/konfiguration.md`
- `de/book/environment.md`

### CODE REVIEW

**Comment by amtoine** [comment]
thanks @ysthakur for the help :pray: 

with this last commit, the only mentions to `let-env` remaining come from
- the blog which we won't change
- the `commands/` which is automatically generated
- the german book in `de/`
- the chinese book in `zh-CN/`

**Comment by sholderbach** [comment]
Is this ready to land?

**Comment by amtoine** [comment]
> Is this ready to land?
>
for the english part, yes.
but for the other languages, you can see above that the german and chinese books are not done :thinking:

**Comment by sholderbach** [comment]
The translations are sadly always a bit behind the curve. Let's merge, so anyone translating gets the benefit of a semi-good English referecne.

I can take a look at the German one later.

**Pull request merged**
