### PR TITLE
add reference to reduce with example

### PR DESCRIPTION
**Pull request by fellnerse**

### CODE REVIEW

**Comment by rgwood** [comment]
Hi, thanks for the PR!

I'm not quite sure how to word this. Your example is converting a list of records (a table) to a single record; I understand [your motivation for doing this](https://github.com/nushell/nushell/discussions/5032) but the description doesn't make that clear. I'm not sure this would make sense to someone reading the docs for the first time. Hmmm.

**Comment by rgwood** [comment]
Gave this a bit more thought.

I think the end of [the Tables section](https://www.nushell.sh/book/types_of_data.html#tables) would be a better place for it (since by then, the reader would have more understanding of tables and records). Maybe with a wording like "To convert 2 columns of a table to a single record:"

**Comment by rgwood** [comment]
Hmm. I think that particular example might be a little confusing, because if a/b/c/d are known ahead of time `{a: b, c: d}` is a simpler way to create that record. Documentation is hard 😅

**Comment by fdncred** [comment]
are we still working on this? if not, let's close it.

**Pull request closed without merging**
