### PR TITLE
DOC: generate the documentation with `make_docs.nu`

### PR DESCRIPTION
**Pull request by amtoine**
as i was writing #803, i found that pending changes to the documentation were a bit getting in the way of my tests, so i thought i could generate the documentation and have them in the website :yum: 

This has been generated with `nushell` on revision `a7b5bd18ba6a068893f5aa8be68883ee0a3d9342` by running a single
```bash
nu make_docs.nu
```
and adding all files to the stage :+1: 

## main changes
- bump the version to `0.76.1`
- add the new `http` subcommands
- add the new `old-alias` command
- integrate minor tweaks to a bunch of commands

### CODE REVIEW

**Comment by sholderbach** [comment]
We try to only show the released versions on the command docs online to not confuse the regular users that don't build bleeding edge. (Only exception is the long form documentation were we are only trying to stay up to date in a best effort sense.)

**Comment by amtoine** [comment]
> We try to only show the released versions on the command docs online to not confuse the regular users that don't build bleeding edge. (Only exception is the long form documentation were we are only trying to stay up to date in a best effort sense.)
>
should i revert the version bump? maybe :thinking:

**Comment by amtoine** [comment]
or should the entire PR wait for the new official release? :open_mouth:

**Comment by fdncred** [comment]
@amtoine let's wait for the next release please. closing for now, but that's for your attentiveness.

**Comment by amtoine** [comment]
> @amtoine let's wait for the next release please. closing for now, but that's for your attentiveness.
>
no worries, that is an issue to generate PR :wink: 
i thought maybe it would be ok :yum:

**Comment by amtoine** [comment]
to address the issue of the "latest main", maybe there could be two "channels" for the website
- one that builds the latest `main` of `nushell.github.io`
- another one that builds only the last tag for instance

that way, this repo would be up to date with main `nushell` without breaking the website for people who do not build `nushell` to the latest revision :yum:

**Pull request closed without merging**
