### PR TITLE
Update cheat_sheet.md

### LINKED ISSUE #1262: Explanations in the cheat sheet should come before the code that's explained
I could open a PR making this change.

I think it'd be much more readable if the explanations weren't  `> quotes` and if they came before the code they explain. I've gotten confused many times when reading it, thinking one explanation belongs to another piece of code.

Also I think many other parts of the book also show the explanation before the example and I think this change would go in line with that.

### PR DESCRIPTION
**Pull request by Kissaki**
Fixes #1262

This change fixes a few issues the cheat sheet had, and makes some additional improvements:

* Drop non-printable characters
* Use description text instead of formatting them as quotes
* Description before code (block/case titles/headlines) (like suggested in #1262, which I agree with)
* Use imperative mood (for the most part)
* Some wording improvements
* Some conciseness improvements (a cheat sheet should be concise, specific, and generalized at the same time)
* Consistently use `>` for commands and add missing returns (some code lines were missing, mixed, or wrong)

### CODE REVIEW

**Comment by fdncred** [comment]
ok, thanks.

**Comment by fdncred** [comment]
Now that I look at the rendering, the top part doesn't look as good without the nushell syntax highlighting.
image

**Comment by Kissaki** [comment]
I guess I'll change those back to code blocks then

**Comment by Kissaki** [comment]
I agree it looks better with syntax highlighting

**Pull request merged**
