### PR TITLE
Add a cookbook comparing jq and nushell

### PR DESCRIPTION
**Pull request by arnau**
Hi, this PR adds a new cookbook comparing jq and nushell as suggested by @fdncred in https://github.com/arnau/seachess/issues/35

I translated my original blog post using a hopefully  better outline for incrementally introduing new Nushell commands and concepts.

I would appreciate an extra eye on the written English. I'm not a native speaker so I'm sure I've done at least some silly mistakes. 🙇

### CODE REVIEW

**Review by fdncred — APPROVED** [review]
This looks fantastic! Thank you so much. I read it and tweaked it a little bit. We really appreciate you adding this great learning utility.

**Comment by arnau** [comment]
@fdncred I see you removed the `>` which I added because I saw them used in other cookbooks. I definitely prefer not having them around. Should we perhaps remove them from all other cookbooks? happy to raise a PR for it.

**Comment by amtoine** [comment]
@arnau 
i'd say it depends :wink: 

here i find it better without them, completely agree :ok_hand: 
a place where it's usefull, we you have a command and it's return value in the same cell
```nushell
> [1, 2, 3] | math sum
6
```

**Comment by arnau** [comment]
@amtoine fair. I guess I prefer to split the return value out. More verbose and takes much move vertical space though 🤷

**Comment by amtoine** [comment]
> @amtoine fair. I guess I prefer to split the return value out. More verbose and takes much move vertical space though 🤷
>
i reviewed your PR :wink: 
i'm open to other feedback on that question, at least the two ways share the same information, so that's the most important :pray:

**Comment by fdncred** [comment]
I just said this in the other PR but I'll say it here too. My preferences is to have the command in a code block without the `>` and the output in a separate code block. If we have them both the command and the output in one code block, then it should keep the `>`.

**Pull request merged**
