### PR TITLE
Fix typos and EOL whitespace

### PR DESCRIPTION
**Pull request by waldyrious**
This PR was triggered by noticing one of the typos that was fixed in https://github.com/nushell/contributor-book/pull/16 (namely, "contributers" --> "contributors").

### CODE REVIEW

**Comment by jonathandturner** [comment]
The documentation for commands is auto-generated. You might want to check if the original command help files have the spaces. If they don't, it might be something the tool is adding.

**Comment by waldyrious** [comment]
Thanks for the heads-up. Indeed most of these are fixable in the source. I've submitted https://github.com/nushell/nushell/pull/1481 and will rebase this PR once those changes propagate to this repo.

**Comment by waldyrious** [comment]
> once those changes propagate to this repo.

Looks like that's somewhat of a manual process :) for starters, I've created #43 to update the docs with the current 0.11.0 release. Once the next release is cut, including the changes from https://github.com/nushell/nushell/pull/1481, I'll do another update for the docs.

After that, most of the changes in this PR will be redundant; I'll rebase the branch at that time, so that any remaining changes can be merged.

**Comment by jonathandturner** [comment]
Since we merged #43, this one might need an update to land

**Comment by jonathandturner** [comment]
Oops, @waldyrious didn't see your latest comment until just now. That sounds good.

**Comment by jonathandturner** [comment]
Looks like these got updated with #44. Would it be safe to close this PR?

**Comment by waldyrious** [comment]
Thanks for the ping! I'll review later today to make sure, and will close if indeed it's fully redundant 👍

**Comment by waldyrious** [comment]
@jonathandturner I've rebased the branch — it now includes only the additional changes (those that didn't concern the commands' documentation).

**Comment by jonathandturner** [comment]
@waldyrious great, thanks. Looks good :)

**Pull request merged**
