### PR TITLE
Releae notes for dirs commands

### PR DESCRIPTION
**Pull request by bobhy**

### CODE REVIEW

**Comment by fdncred** [comment]
I'm wondering if we should include this or not in the release notes since std.nu isn't really a thing yet. Granted dirs.nu is in the repository, but I'm just not sure. What do others think?

**Comment by amtoine** [comment]
> I'm wondering if we should include this or not in the release notes since std.nu isn't really a thing yet. Granted dirs.nu is in the repository, but I'm just not sure. What do others think?
>
maybe this should come after a "true" announce of the standard library? :thinking:

**Comment by kubouch** [comment]
Let's put this to the next release notes

**Comment by bobhy** [comment]
Hmm, the dirs work is not tightly integrated with std.nu. we don't even
have to say anything about std.nu right now, if we're not ready.  This
is"just" an alternative implementation and doesn't make any changes to
user's environment (unless user does it themselves). So I'd say it's ok to
ship this pre std (speaking impartially, even though it's my feature).

Regards
Bob

**Pull request closed without merging**
