### PR TITLE
Fix a sample code on the "moving around" chapter

### PR DESCRIPTION
**Pull request by ohno418**
Remove hidden files from the result of `ls` command. It doesn't seem to output hidden files.

### CODE REVIEW

**Comment by sholderbach** [comment]
Thanks for catching that discrepancy. Interestingly adding `-a` doesn't seem to change that. So this might be a regression we need to address in general.

**Comment by fdncred** [comment]
It looks like it's platform dependent maybe? This is from Windows.
image

**Comment by fdncred** [comment]
On Linux with 0.69.2 I get this:
image

and `ls -a`
image

**Comment by sholderbach** [comment]
On linux `ls` vs `ls -a` behaves as expected. The problem is the inconsitent behavior with a glob e.g. `ls **/*.md` vs `ls -a **/*.md`

**Comment by sholderbach** [comment]
Apart from the bug there let's move forward with your PR.

**Comment by sholderbach** [comment]
OK, gave this a test drive on linux again: `ls -a <GLOB>` seems to behave as expected as well. (was mistakenly running in the docs repo instead of the nushell source repo)

**Pull request merged**
