### PR TITLE
mark feature-gated commands more clearly

### PR DESCRIPTION
**Pull request by amtoine**
currently, the only way to tell whether a command is from the default set of commands or not is to go to the very bottom of a command help page and see if there is a "tip" mentionning a feature.
this is pretty hard to see and can be quite confusing the doc...
feature-command-tip

## description
this PR
- move the "tip" from the bottom of the pages to the top, as a real Vuepress warning
featured-command-warning
- add the feature of a command to its frontmatter
- adds a "Feature" column to the [main command page](https://www.nushell.sh/commands/) to show the feature of each command
alias-default
dfr-feature-column
math-sin-feature

### CODE REVIEW

**Comment by amtoine** [comment]
i did not generate the documentation page themselves for now...
@hustcer you might know how to do that and deploy the website? :innocent:

**Comment by amtoine** [comment]
conflict introduced by https://github.com/nushell/nushell.github.io/pull/1199 solved in 191bc1b1

**Comment by fdncred** [comment]
sorry for the conflict - we should probably just land this and see what happens. the docs should be re-ran shortly after the next release.

**Comment by amtoine** [comment]
no worries!

we can land this for sure

**Comment by hustcer** [comment]
I have pulled the latest `main` and tried the new script locally, it works perfect, thanks!

**Pull request merged**
