### PR TITLE
More generic `describe` usage

### PR DESCRIPTION
**Pull request by flying-sheep**

### CODE REVIEW

**Comment by fdncred** [comment]
I'm not sure it's a good idea to change it here since these files are programmatically generated. There are apparently 3 describe commands that will be used depending on context. You can see them with `help describe`. There's one for "normal" usage, one for DB, and one for Dataframes. What we need to be able to do is infer the correct one at the correct time.

**Comment by flying-sheep** [comment]
well, if “help describe” shows all three, the “describe” online docs should too. The two I merged here have a very comparable purpose, the 3rd one does column statistics on a dataframe.

Instead we have 2 somehow.

**Comment by fdncred** [comment]
>  if “help describe” shows all three, the “describe” online docs should too.

agree.

@hustcer what do you think? do we need to update our doc generation script?

**Comment by hustcer** [comment]
@fdncred Sorry for the late reply, I just saw this. It's a good idea to update the doc generation script and vue-press page rendering related stuff as the commands' doc layout will be changed a lot. It's not an easy task, PR is welcomed.

**Comment by fdncred** [comment]
closing this because it needs to be done via the script.

**Pull request closed without merging**
