### PR TITLE
Add separate page for setting Nu as default shell

### PR DESCRIPTION
**Pull request by Hofer-Julian**
- Adds instructions to add Nu to your terminal
- Advises against setting Nu as login shell

Heavily inspired by
https://elv.sh/get/#using-elvish-as-your-default-shell

### CODE REVIEW

**Comment by fdncred** [comment]
I like the changes except that the part that says "We do not recommend setting your login shell to Nu.". I use it as my login shell in WSL2 every weekday without issue. I can understand that we may need to say something but I don't want to deter people from using nushell, just the opposite.

I think it's ok to have a warning but I think we should use different words. Perhaps like "Warning, Nu is still in development and is not intended to be POSIX compliant. If you need strict POSIX compliance at login time, you should consider using a alternate login shell."

Maybe not those exact words, but something less like "Don't use nushell" 😆

**Comment by Hofer-Julian** [comment]
> Maybe not those exact words, but something less like "Don't use nushell" 

I understand what you are saying, and I also want people to use nushell.
Even as their default shell, which is why I've added the terminal instructions.

> If you need strict POSIX compliance at login time

Unfortunately, that's not something you can choose.
There are just too many programs who just assume that your login shell is POSIX compliant, and the error messages tend to be very bad and/or hidden somewhere in the logs.

Some friends noticed that also with some vscode extensions, so that problem probably also occurs on WSL and macOS.

If you still want me to weaken the message or add alternative "default methods" (see https://wiki.archlinux.org/title/Fish), I am happy to.

**Comment by fdncred** [comment]
Yes, it needs to be similar to what I suggested please. I don't want to discourage use.

**Comment by Hofer-Julian** [comment]
Updated it to:
> Nu is still in development and is not intended to be POSIX compliant.
Be aware that some programs on your system might assume that your login shell is [POSIX](https://en.wikipedia.org/wiki/POSIX) compatible.
Breaking that assumption can lead to unexpected issues.

How do you like that one?

**Comment by fdncred** [comment]
Much better. Thank you.

**Comment by fdncred** [comment]
One last thing, Do you think the `installation` page should have a link to the `default_shell` page? I could go either way.

**Comment by Hofer-Julian** [comment]
vuepress does that for us at the very end of the page.
I feel like that is sufficient :)

grafik

**Comment by rgwood** [comment]
Thanks for improving the docs!

**Pull request merged**
