### PR TITLE
TEST: try to change a command documentation file

### PR DESCRIPTION
**Pull request by amtoine**
related to https://github.com/nushell/nushell.github.io/pull/969

## :warning: THIS IS A TEST, DO NOT MERGE

### CODE REVIEW

**Comment by amtoine** [comment]
cc/ @sholderbach 

looks like there is an issue with the comment workflow :thinking:

**Comment by sholderbach** [comment]
Mhh, weird it went through in sholderbach/nushell.github.io#1

There I was both repo owner and PR actor?

**Comment by amtoine** [comment]
> Mhh, weird it went through in [sholderbach#1](https://github.com/sholderbach/nushell.github.io/pull/1)
>
yeah i saw this PR and it was working there :thinking: 
 
> There I was both repo owner and PR actor?
>
maybe there is some kind of permission issue :confused:

**Comment by fdncred** [comment]
It would be nice if this CI could add a comment to the issue. I think a lot of people just see the red CI and don't understand how to see what the problem is.

**Comment by amtoine** [comment]
yeah i agree :thinking: 

@sholderbach 
still no clue what is happening here? :confused:

**Comment by sholderbach** [comment]
Not really sure either how to investigate this. I stackoverflowed the initial attempt together on my fork. The well documented parts of the GH api seem to deal with authentications through direct tokens as you would do if you ran your own service to talk to github. Not quite sure what is going wrong with how I am using the https://github.com/actions/github-script action

**Comment by fdncred** [comment]
hasn't been messed with in a while, so closing.

**Pull request closed without merging**
