### PR TITLE
fill contents to handling stderr

### PR DESCRIPTION
**Pull request by WindSoilder**
This is a follow up to https://github.com/nushell/nushell/pull/11708

Which introduces all rules to redirections and pipes

### CODE REVIEW

**Comment by kubouch** [comment]
Looks good. We might want to split the document up at some point, but that could be done later. 

The examples with `nu --testbin echo_env_mixed out-err FOO BAR` might not be clear. Even though it's defined in the code block at the top, maybe it would be clearer to wrap it in a custom command, like `def print-to-stdout-stderr [] { nu --testbin ... }`.

One more thing we could do is change the title from `Handling stderr` to `Handling stdout and stderr` because both are being discussed. And it could be mentioned at the top that it works only for external streams because Nushell doesn't have stdout/stderr.

I like the style overall, mostly tables and short examples. Some minor grammar things that we can check once it's ready.

**Comment by WindSoilder** [comment]
> The examples with nu --testbin echo_env_mixed out-err FOO BAR might not be clear. Even though it's defined in the code block at the top, maybe it would be clearer to wrap it in a custom command, like def print-to-stdout-stderr [] { nu --testbin ... }

Sadly I think `print-to-stdout-stderr` won't work, because it's not external command.  I've update the example to use a script called `demo.nu`, then we can interactive with the script.

**Comment by kubouch** [comment]
@WindSoilder Looks good to me. I updated some language and also made the tables more structured. If you're fine with that, feel free to merge. Thanks for clarifying the different redirection styles, it's now much cleaner!

**Comment by WindSoilder** [comment]
Thank you for the change!

**Pull request merged**
