### PR TITLE
Add french translation [#1532]

### PR DESCRIPTION
**Pull request by LoicRiegel**
# Start a French translation

Linked issue: #1532

### I started this translation by translating:
- the landing page
- the book's landing page
- the book's "Getting started" section

### How I did it / my approach:

I used ChatGPT to get a first translation draft. Then I carefully proofread everything and rephrased where needed.
My approach was:
- stay as close as possible as the english version (e.g. how the sentence is built)
- translate technical terms in french as much as possible, but allow some technical words to remain in English. Examples: "wildcard", "raw" (in "raw strings")
- when the docs points to another document that is not translated for now, point to the english version
- I checked especially links
- All code snippets are strictly the same as the english version

### Other thoughts:
Honestly it's sometmes quite hard to find a good translation! Being used to reading and working with code in English every day, this made me realize how much we use English for programming concepts and vocabulary. Sometimes we "englishize" some words, even when a french equivalent might exist... 
Anyway, I did my best! But I think another review by a fellow french contributor could still be nice 😄

### CODE REVIEW

**Comment by LoicRiegel** [comment]
@hustcer the PR is ready: I did the commit cleanup I wanted. Could you approve the workflows to run? Is there something else to do?

**Comment by fdncred** [comment]
lol, looks like spell check doesn't like french. i'm sure there is some way to add that folder to be ignored by spell check but i'm not sure what it is.

**Comment by LoicRiegel** [comment]
> lol, looks like spell check doesn't like french. i'm sure there is some way to add that folder to be ignored by spell check but i'm not sure what it is.

Does the spell checker know about the other languages? German, spanish etc? Or are they also excluded from the check already?

**Comment by fdncred** [comment]
> Or are they also excluded from the check already?

I'm guessing they're excluded but I'm not sure. You'll have to dig around the repo and look.

**Comment by LoicRiegel** [comment]
> I'm guessing they're excluded but I'm not sure. You'll have to dig around the repo and look.

Okay, wasn't too hard to find actually :)

**Comment by LoicRiegel** [comment]
> > I'm guessing they're excluded but I'm not sure. You'll have to dig around the repo and look.
> 
> Okay, wasn't too hard to find actually :)

Could you trigger the workflows again please?

**Comment by hustcer** [comment]
@LoicRiegel Great work and a huge thanks, I will review it in a few hours 👍

**Comment by hustcer** [comment]
@LoicRiegel It looks good to me except that the commit SHA is too long for a table cell in `i18n-meta.json`, it's recommend to use the output of `git rev-parse --short HEAD` instead. 
BTW: I don't know French so I won't read the translation itself.

**Comment by fdncred** [comment]
maybe @amtoine can skim the text?

**Comment by LoicRiegel** [comment]
> @LoicRiegel Great work and a huge thanks, I will review it in a few hours 👍

You're welcome! It did take a few hours 😄 

I modified the last commit so that i18n meta has the short commit SHA.

**Comment by amtoine** [comment]
grrr NPM does not want to run the website locally... i hate it each time :sob:

**Comment by hustcer** [comment]
@LoicRiegel  Sorry to keep you waiting, do you want to land this now or do you want to keep on translating more docs on this pr?

**Comment by LoicRiegel** [comment]
> @LoicRiegel Sorry to keep you waiting, do you want to land this now or do you want to keep on translating more docs on this pr?

No worries :) No I won't translate more documents in the PR. However I can wait for the review from @amtoine or someone else

**Comment by fdncred** [comment]
antoine mentioned that he doesn't really have time so if @hustcer is good we can land this

**Comment by amtoine** [comment]
yeah there is a lot to read and then, if the English documentation changes, this implies an extra maintenance burden :confused:

**Comment by LoicRiegel** [comment]
Okay sure, let's land this then :)
The commits on this branch are good, though behind the main branch now. I can rebase if you want, otherwise I'll let you merge 🚀

**Comment by fdncred** [comment]
Thanks

**Comment by amtoine** [comment]
thanks @LoicRiegel :pray: 

no need to rebase when there are no conflicts :wink:

**Pull request merged**
